# Generated by Django 2.2.1 on 2019-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
